security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    naoual: { password: naoual142, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/manager/*
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /manager/upload
                csrf_provider: form.csrf_provider
            logout:
                path:   logout
                target: /login
            anonymous: true
            security: true
            remember_me:
                key:      "%secret%"
                lifetime: 7200 # en secondes
                path:     /
                domain:   ~

        login:
            pattern:  ^/login
            anonymous: true
        


    access_control:
    
       # ROLE USER SUPREME: RECHERCHE ET ACCESS CONTROL
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/manager/*, roles: ROLE_ADMIN, requires_channel: http }
        
        
        
        
        
        
        
        
        
        
        
