p_homepage:
    pattern:  /manager/upload/{valide}
    defaults: { _controller: PBundle:Default:index, valide:0 }

    
p_ajax:
    pattern:  /manager/ajax
    defaults: { _controller: PBundle:Default:ajaxData }
        
    
p_stats_hf_nbr:
    pattern:  /manager/stats/hf_nbr
    defaults: { _controller: PBundle:stats:hf_nbr }
        
    
    
p_stats_date:
    pattern:  /manager/stats/par_date
    defaults: { _controller: PBundle:stats:par_date }
        
    
indicateur_stats:
    pattern:  /manager/stats/indicateur
    defaults: { _controller: PBundle:stats:indicateur }
        
    
    

    
# FIN SECTION CALENDRIER -----------------------------------------------
    
calendar:
    pattern:  manager/calendar
    defaults: { _controller: PBundle:Calendar:index }


calendar_ajouter:
    pattern:  manager/calendar/add/ajax
    defaults: { _controller: PBundle:Calendar:ajouter }


calendar_modifier:
    pattern: manager/calendar/up/ajax
    defaults: { _controller: PBundle:Calendar:modifier }



calendar_supprimer:
    pattern:  manager/calendar/spr/ajax
    defaults: { _controller: PBundle:Calendar:supprimer }

    
# FIN SECTION CALENDRIER -----------------------------------------------
    
    