p_homepage:
    pattern:  /hello/{valide}
    defaults: { _controller: PBundle:Default:index, valide:0 }

    
p_ajax:
    pattern:  /ajax
    defaults: { _controller: PBundle:Default:ajaxData }
        
    
p_stats_hf_nbr:
    pattern:  /stats/hf_nbr
    defaults: { _controller: PBundle:stats:hf_nbr }
        
    
    
p_stats_date:
    pattern:  /stats/par_date
    defaults: { _controller: PBundle:stats:par_date }
        
    
indicateur:
    pattern:  /stats/indicateur
    defaults: { _controller: PBundle:stats:indicateur }
        
    